### PR TITLE
Add support for eo

### PR DESCRIPTION
**Pull request by Wafelack**
# Pull request

##### Fill either one
- [ ] Does your pull request add a crate?
- [x] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [x] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

### CODE REVIEW

**Comment by Gitleptune** [comment]
very blazingly memory safe!!! 🚀🌕

_This comment was supported by [lantern theme](https://github.com/gitleptune/lantern-theme)! 🚀_

**Comment by mTvare6** [comment]
@Wafelack why do you want everyone to know you use [vim](https://github.com/mTvare6/hello-world.rs/pull/50/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR605)

**Comment by Wafelack** [comment]
My bad, I did not see it.

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Comment by mTvare6** [comment]
Don't advertise

**Pull request merged**
