### PR TITLE
added 50 useless crates 🚀

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

# Pull request

##### Fill either one
- [x] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [x] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

### CODE REVIEW

**Comment by TruncatedDinosour** [comment]
(sorry for being annoying)

**Comment by mTvare6** [comment]
You do not add random 50 crates, you add 1 crate which has 50 dependencies. I also recommend compiling it before making a pr.

**Comment by monosans** [comment]
> I also recommend compiling it before making a pr.

Why not just enable CI for PRs?

**Comment by TruncatedDinosour** [comment]
sorry

**Pull request closed without merging**
