### PR TITLE
Add a translation in C

### PR DESCRIPTION
**Pull request by TruncatedDinoSour**
# Pull request

##### Fill either one
- [ ] Does your pull request add a crate?
- [x] Does your pull request add a new language?

- [ ] Is your pull request memory safe?
- [ ] Is your pull request configurable?
- [ ] Is your pull request minimal?
- [ ] Is your pull request blazing fast?
- [x] Is your request C(ringe), C(ve) and C(bad) (:vomiting_face:) (C bad rust good), C is not memory safe, not configurable, not minimal and very turtle and slow bc C is C rust is 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

### CODE REVIEW

**Review by CorruptedVor — APPROVED** [review]

**Comment by TruncatedDinosour** [comment]
😳

**Comment by TruncatedDinosour** [comment]
> 👎
> 
> Definitely do not merge: this suggested code is clearly unsafe (since it is C) and cannot be made safe (since it is C).

i think youre misunderstanding me, i think this should indeed get merged because rust, as a totally supreme, safe, memory safe, safe, safe, not unsafe, very safe language ( btw its memory safe ), should be the mature one and show dominance over the ( c )ringe and bad c "developers" ( yeah right ) which use a cringe and cve language known as c 🤮

**Comment by jagerman** [comment]
> i think youre misunderstanding me, i think this should indeed get merged because rust, as a totally supreme, safe, memory safe, safe, safe, not unsafe, very safe language ( btw its memory safe ), should be the mature one and show dominance over the ( c )ringe and bad c "developers" ( yeah right ) which use a cringe and cve language known as c vomiting_face

Someone might not understand that, though, and might think that because this output was produced by a rust program that therefore it is safe.

Ideally an unsafe block should be required to print content like this from Rust, but that feature hasn't been added to rustc yet.

**Comment by TruncatedDinosour** [comment]
> > i think youre misunderstanding me, i think this should indeed get merged because rust, as a totally supreme, safe, memory safe, safe, safe, not unsafe, very safe language ( btw its memory safe ), should be the mature one and show dominance over the ( c )ringe and bad c "developers" ( yeah right ) which use a cringe and cve language known as c vomiting_face
> 
> Someone might not understand that, though, and might think that because this output was produced by a rust program that therefore it is safe.
> 
> Ideally an unsafe block should be required to print content like this from Rust, but that feature hasn't been added to rustc yet.

i think rust should add a `safe::!<>` block to indicate how safe rust is

```rs
safe::!<> {
    println!("hello world");
}
```

**Comment by TruncatedDinosour** [comment]
!!!! add c

**Comment by TruncatedDinosour** [comment]
we need to show c 'developers' how safe and good and memory safe rust is by showing how slow and cringe c ( * ) is

**Comment by mTvare6** [comment]
lgtm

**Pull request merged**
