### PR TITLE
added 67480 crates

### PR DESCRIPTION
**Pull request by zemlyak**
# Pull request

##### Fill either one
- [x] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [ ] Is your pull request memory safe?
- [ ] Is your pull request configurable?
- [ ] Is your pull request minimal?
- [ ] Is your pull request blazing fast?

this has been done entirely by a bash script, and therefore, does not compile🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

### CODE REVIEW

**Comment by alexislefebvre** [comment]
This will block future contributions since no one will be able to add crates.

**Review by TheDevMinerTV — APPROVED** [review]

**Comment by binex-dsk** [comment]
Any progress on this?

**Comment by binex-dsk** [comment]
> @zemlyak We do not add 10 crates to increase crate count by 10, we add 1 crate to increase crate count by 100, like amethyst with a lot of dependencies, plus, hello world.rs must be compilable as its used by enterprise level customers

Progress on this? Would like this implemented.

**Comment by overlisted** [comment]
There are too many dependency conflicts

**Comment by binex-dsk** [comment]
ZAD :(

**Comment by maxwase** [comment]
Did you run `cargo tree -d` to check dependencies duplication?

**Comment by shitpostbotmin** [comment]
LGTM

**Pull request closed without merging**
