### PR TITLE
Makes the english hello world posix compliant and conform to gnu hello(1)

### PR DESCRIPTION
**Pull request by legendofmiracles**
##### Fill either one
- [ ] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [x] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

🚀 
this program should be a drop-in replacement for gnu hello in production, it is critical that it works in the same way

### CODE REVIEW

**Comment by mTvare6** [comment]
@legendofmiracles did you fix every language? else its racistic towards people of other ethnicity and culture which is definitely not what our enterprise level customers would want

**Comment by legendofmiracles** [comment]
fuck off

**Comment by legendofmiracles** [comment]
@mTvare6 Thank you for your feedback, that is obviously not what we intend to do - so I updated my PR to include all language where I can reliably say that the comma is in the right position. The maintainers of the other language will have to add the commas themselves

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Pull request merged**
