### PR TITLE
Add French

### PR DESCRIPTION
**Pull request by Nioobers**
Add French translation

### CODE REVIEW

**Comment by monosans** [comment]
You should also add French to `src/main.rs`, otherwise it will have no effect and people won't be able to print "Bonjour Monde!" blazingly fast with 🚀Rust's🚀 memory safety.

**Comment by Nioobers** [comment]
Ah, excuse me, I had forgotten.

**Comment by Nioobers** [comment]
*I'm dumb, I already deleted the fork*

**Comment by Nioobers** [comment]
having a bit of trouble with git, would it bother if I made a second pull request? (I've tried almost everything, I can't seem to add a second commit to my pull request (although it may have been a very stupid thing that jumped out))

**Pull request merged**
