### PR TITLE
Add PKGBUILD for Arch Linux

### PR DESCRIPTION
**Pull request by monosans**
# Pull request

##### Fill either one
- [ ] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [X] Is your pull request memory safe?
- [X] Is your pull request configurable?
- [X] Is your pull request minimal?
- [X] Is your pull request blazing fast?

### CODE REVIEW

**Comment by mTvare6** [comment]
This feels like toooo much trolling though, for people who actually want to get it from the AUR, can you get the dependencies from README.md and add them? maybe comment out the current dependencies line without removing it completely so I can add it later if I want

**Comment by monosans** [comment]
> This feels like toooo much trolling though, for people who actually want to get it from the AUR, can you get the dependencies from README.md and add them? maybe comment out the current dependencies line without removing it completely so I can add it later if I want

I can add all these as optional dependencies though :)

**Comment by mTvare6** [comment]
> > This feels like toooo much trolling though, for people who actually want to get it from the AUR, can you get the dependencies from README.md and add them? maybe comment out the current dependencies line without removing it completely so I can add it later if I want
> 
> I can add all these as optional dependencies though :)

Do it then :)

**Comment by monosans** [comment]
@mTvare6 done. I should note that I have not tested if this works. I think someone has to test it before our enterprise users try it out.

**Comment by mTvare6** [comment]
@monosans It depends on few other things too

<div>1. <a href="https://www.cairographics.org/download/">cairo development libraries</a> 🚀.</div>
<div>1. <a href="https://www.gtk.org/docs/installations/">libgtk development libraries</a> 🚀.</div>
<div>1. alsa-lib 🚀</div>
<div>1. glfw 🚀</div>
<div>1. freetype 🚀</div>
<div>1. libglib 🚀</div>
<div>1. pango 🚀</div>
<div>1. atk 🚀</div>
<div>1. pixbuf 🚀</div>
<div>1. gdk 🚀</div>

Maybe can you try to get them? if not its fine, I will search for them

**Comment by monosans** [comment]
> @monosans It depends on few other things too
> 
> 1. [cairo development libraries](https://www.cairographics.org/download/) .
> 1. [libgtk development libraries](https://www.gtk.org/docs/installations/) .
> 1. alsa-lib 
> 1. glfw 
> 1. freetype 
> 1. libglib 
> 1. pango 
> 1. atk 
> 1. pixbuf 
> 1. gdk 
> Maybe can you try to get them? if not its fine, I will search for them

🚀Ready🚀

**Comment by legendofmiracles** [comment]
It also depends on python3

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world` in AUR

**Comment by sickcodes** [comment]
> This feels like toooo much trolling though, for people who actually want to get it from the AUR, can you get the dependencies from README.md and add them? maybe comment out the current dependencies line without removing it completely so I can add it later if I want

You just mark it out of date immediately, but it must be done blazingly fast 🚀

**Pull request merged**
