### PR TITLE
add indonesian translation

### PR DESCRIPTION
**Pull request by styd**
# Pull request

##### Fill either one
- [ ] Does your pull request add a crate?
- [x] Does your pull request add a new language?

- [X] Is your pull request memory safe?
- [X] Is your pull request configurable?
- [X] Is your pull request minimal?
- [X] Is your pull request blazing fast?

### CODE REVIEW

**Comment by mTvare6** [comment]
This sounds so similiar to Arabic or Hindi

**Comment by styd** [comment]
> This sounds so similiar to Arabic or Hindi

Yes, it seems so.
> The [Indonesian language](https://en.wikipedia.org/wiki/Indonesian_language) has absorbed many [loanwords](https://en.wikipedia.org/wiki/Loanword) from other languages, [Sanskrit](https://en.wikipedia.org/wiki/Sanskrit), [Chinese](https://en.wikipedia.org/wiki/Chinese_language), [Japanese](https://en.wikipedia.org/wiki/Japanese_language), [Arabic](https://en.wikipedia.org/wiki/Arabic_language), [Hebrew](https://en.wikipedia.org/wiki/Hebrew_language), [Persian](https://en.wikipedia.org/wiki/Persian_language), [Portuguese](https://en.wikipedia.org/wiki/Portuguese_language), [Dutch](https://en.wikipedia.org/wiki/Dutch_language), [English](https://en.wikipedia.org/wiki/English_language), and other [Austronesian languages](https://en.wikipedia.org/wiki/Austronesian_languages).

source: https://en.wikipedia.org/wiki/List_of_loanwords_in_Indonesian

You can check in google translate here:
https://translate.google.com/?sl=id&tl=en&text=Halo%2C%20Dunia!&op=translate

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Pull request merged**
