### PR TITLE
Fix french translations

### PR DESCRIPTION
**Pull request by Bqleine**
Added a non breaking space before the exclamation point.

### CODE REVIEW

**Comment by mTvare6** [comment]
This is the second time I get a pr like this, is this an essential feature of french?

**Comment by neilbryson** [comment]
It is done in European French for symbols like `!`, `?`, `:` and `;`. Nothing too major, but this is definitely practiced.

**Comment by mTvare6** [comment]
Fixed as of #254

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Comment by Bqleine** [comment]
> This is the second time I get a pr like this(#254), is this an essential feature of french?

fyi, this comes from typographic rules that need to be respected when typing French. Such rules also exist in many other languages. See https://en.wikipedia.org/wiki/Style_guide and https://en.wikipedia.org/wiki/List_of_style_guides

**Pull request merged**
