### PR TITLE
Add newline when printing on shells so it doesn't break prompts on some shells as this can be a frustrating issue for people who don't use zsh

### PR DESCRIPTION
**Pull request by BBaoVanC**
# Pull request

##### Fill either one
- [x] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [ ] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

### CODE REVIEW

**Comment by BBaoVanC** [comment]
oh i guess i need a different library to replace setenv

**Comment by BBaoVanC** [comment]
https://stackoverflow.com/a/3327022 for reference

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Comment by BBaoVanC** [comment]
idk why it's saying those are new vulnerabilities introduced by my PR, they're already there on master

**Comment by jagerman** [comment]
> idk why it's saying those are new vulnerabilities introduced by my PR, they're already there on master

Don't worry, rust is safe, so vulnerabilities can't affect you.

**Pull request merged**
