### PR TITLE
Add Russian

### PR DESCRIPTION
**Pull request by monosans**
🚀🚀🚀🚀🚀

### CODE REVIEW

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like echo with very minimal, blazing fast, and configurable hello-world

**Comment by LoganDark** [comment]
This PR should be reverted🚫, it's very insecure now. Rust(:rocket:) can't serve bad country like Russian🇷🇺 language support is used to attack Ukraine🇺🇦.

**Comment by mTvare6** [comment]
Tolerance

**Comment by LoganDark** [comment]
> Tolerance

image

**Pull request merged**
