### PR TITLE
Use `safe!` macro to take advantage of Rust(🚀)'s safety guarantees and make hello-world.rs even more safe 🚀

### PR DESCRIPTION
**Pull request by Omnikar**
# Pull request

##### Fill either one
- [x] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [x] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

### CODE REVIEW

**Comment by mTvare6** [comment]
Doesn't seem to build on my machine, does it on yours?

**Comment by Omnikar** [comment]
I couldn't figure out how to build it in the first place so I just figured that the changes I made wouldn't affect whether it would still build for others

**Comment by mTvare6** [comment]
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

**Comment by mTvare6** [comment]
I deleted the target and it worked on recompiling

**Pull request merged**
